# .github/dependabot.yml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable npm dependencies for the root project
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json
    schedule:
      interval: "weekly" # Check for updates weekly
    # Allow Dependabot to create pull requests automatically
    open-pull-requests-limit: 10 # Limit the number of open PRs to avoid overwhelming

  # Enable npm dependencies for the GitHub scripts
  - package-ecosystem: "npm"
    directory: "/.github/scripts" # Location of package.json in scripts directory
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Enable pip dependencies for Python source
  - package-ecosystem: "pip"
    directory: "/src/python" # Location of requirements.txt
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
