blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/adrianwedd/cv/discussions
    about: Ask questions, share ideas, and discuss the project with the community
  - name: 🔒 Security Vulnerability
    url: https://github.com/adrianwedd/cv/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 📚 Documentation
    url: https://github.com/adrianwedd/cv/blob/main/README.md
    about: Read the full documentation and setup guide
  - name: 🚀 Live Demo
    url: https://adrianwedd.github.io/cv
    about: View the live AI-enhanced CV in action